# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0014_order_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
    ]
